-- GENERATED by scripts/seed-to-sql.mjs — edit src/data/seed.json instead.
--
-- 30 well-known Lower Manhattan locations. NONE verified in person;
-- coordinates are approximate to the building, not the restroom door. No door
-- codes: rows marked code_required simply have no code recorded yet.
-- Amenity flags are null (unknown) rather than guessed.
--
-- Synthetic confirms/troubles from the bundled sample are deliberately NOT
-- carried over — real reports should come from real people.

set search_path = public, extensions;

insert into bathrooms
  (name, geog, venue_type, access_kind, address, floor_hint,
   wheelchair, changing_table, gender_neutral)
select
  v.name,
  st_setsrid(st_makepoint(v.lng, v.lat), 4326)::geography,
  v.venue_type::venue_type,
  v.access_kind::access_kind,
  v.address, v.floor_hint,
  v.wheelchair, v.changing_table, v.gender_neutral
from (values
  ('Battery Park — Castle Clinton', -74.0169, 40.7033, 'park', 'open', 'Battery Park, New York, NY', 'North side of the fort, near the ticket booths', null::boolean, null::boolean, null::boolean),
  ('Bowling Green', -74.0138, 40.7046, 'park', 'open', 'Broadway at Whitehall St', null::text, null::boolean, null::boolean, null::boolean),
  ('Whitehall Terminal (Staten Island Ferry)', -74.0134, 40.7013, 'transit', 'open', '4 Whitehall St', 'Main waiting hall, both ends', null::boolean, null::boolean, null::boolean),
  ('Rockefeller Park, Battery Park City', -74.0169, 40.7168, 'park', 'open', 'River Terrace at Warren St', 'Park house by the playground', null::boolean, null::boolean, null::boolean),
  ('Teardrop Park', -74.0166, 40.7153, 'park', 'open', 'Murray St at River Terrace', null::text, null::boolean, null::boolean, null::boolean),
  ('Wagner Park', -74.0181, 40.7053, 'park', 'open', 'Battery Place at Little West St', null::text, null::boolean, null::boolean, null::boolean),
  ('City Hall Park', -74.0059, 40.7127, 'park', 'open', 'Broadway at Chambers St', null::text, null::boolean, null::boolean, null::boolean),
  ('Columbus Park', -73.9999, 40.7152, 'park', 'open', 'Mulberry St at Bayard St', null::text, null::boolean, null::boolean, null::boolean),
  ('Sara D. Roosevelt Park', -73.9922, 40.7205, 'park', 'open', 'Chrystie St at Broome St', null::text, null::boolean, null::boolean, null::boolean),
  ('Washington Square Park', -73.9973, 40.7308, 'park', 'open', 'Washington Square, New York, NY', 'Southwest corner, near the chess tables', null::boolean, null::boolean, null::boolean),
  ('Duane Park', -74.0079, 40.7194, 'park', 'open', 'Duane St at Hudson St', null::text, null::boolean, null::boolean, null::boolean),
  ('Hudson River Park — Pier 25', -74.0128, 40.7199, 'park', 'open', 'Pier 25, N Moore St', 'Near the mini-golf entrance', null::boolean, null::boolean, null::boolean),
  ('Hudson River Park — Pier 45', -74.011, 40.7343, 'park', 'open', 'Pier 45, Christopher St', null::text, null::boolean, null::boolean, null::boolean),
  ('Elizabeth H. Berger Plaza', -74.0136, 40.7062, 'park', 'open', 'Greenwich St at Trinity Pl', null::text, null::boolean, null::boolean, null::boolean),
  ('Fulton Center', -74.009, 40.7101, 'transit', 'open', '200 Broadway', 'Mezzanine level', null::boolean, null::boolean, null::boolean),
  ('WTC Transportation Hub (Oculus)', -74.0111, 40.7115, 'transit', 'open', 'Church St at Fulton St', 'Lower concourse, west end', null::boolean, null::boolean, null::boolean),
  ('Westfield World Trade Center', -74.011, 40.7112, 'store', 'open', '185 Greenwich St', 'Concourse level, near Eataly', null::boolean, null::boolean, null::boolean),
  ('Brookfield Place — Winter Garden', -74.0155, 40.7127, 'store', 'open', '230 Vesey St', 'Second floor, past Hudson Eats', null::boolean, null::boolean, null::boolean),
  ('Pier 17, South Street Seaport', -74.0029, 40.7057, 'store', 'open', '89 South St', 'Ground floor, north side', null::boolean, null::boolean, null::boolean),
  ('NYPL — Battery Park City', -74.0163, 40.715, 'library', 'open', '175 North End Ave', null::text, null::boolean, null::boolean, null::boolean),
  ('NYPL — Chatham Square', -73.9975, 40.7137, 'library', 'open', '33 East Broadway', null::text, null::boolean, null::boolean, null::boolean),
  ('NYPL — Mulberry Street', -73.9945, 40.7226, 'library', 'open', '10 Jersey St', 'Basement level', null::boolean, null::boolean, null::boolean),
  ('National Museum of the American Indian', -74.0136, 40.7047, 'public_facility', 'open', '1 Bowling Green', 'Ground floor, left of the rotunda', null::boolean, null::boolean, null::boolean),
  ('Trinity Church', -74.0119, 40.7081, 'public_facility', 'ask_staff', '89 Broadway', null::text, null::boolean, null::boolean, null::boolean),
  ('Eataly NYC Downtown', -74.0121, 40.7105, 'restaurant', 'customers_only', '101 Liberty St, 3rd floor', 'Third floor, back past the pasta counter', null::boolean, null::boolean, null::boolean),
  ('Whole Foods — Tribeca', -74.009, 40.7176, 'store', 'open', '270 Greenwich St', 'Back left, past the registers', null::boolean, null::boolean, null::boolean),
  ('Whole Foods — Battery Park', -74.0153, 40.7148, 'store', 'open', '270 Greenwich St', null::text, null::boolean, null::boolean, null::boolean),
  ('Starbucks — Wall Street', -74.009, 40.7069, 'cafe', 'code_required', '55 Broad St', null::text, null::boolean, null::boolean, null::boolean),
  ('Starbucks — Fulton Street', -74.0075, 40.7098, 'cafe', 'code_required', '115 Fulton St', null::text, null::boolean, null::boolean, null::boolean),
  ('Blue Bottle Coffee — FiDi', -74.0102, 40.7063, 'cafe', 'ask_staff', '1 Rector St', null::text, null::boolean, null::boolean, null::boolean)
) as v(name, lng, lat, venue_type, access_kind, address, floor_hint,
       wheelchair, changing_table, gender_neutral);
