#!/usr/bin/env node
// Emits supabase/seed.sql from src/data/seed.json so the bundled sample data
// and the database seed never drift apart.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const rows = JSON.parse(readFileSync(join(root, 'src/data/seed.json'), 'utf8'))

// A bare `null` in a VALUES list carries no type. Every row here is null for
// the amenity flags, so Postgres would infer text for the whole column and
// then refuse to insert it into a boolean. Cast every null explicitly.
const q = (v) => (v === null || v === undefined ? 'null::text' : `'${String(v).replace(/'/g, "''")}'`)
const b = (v) => (v === null || v === undefined ? 'null::boolean' : String(v))

const values = rows
  .map((r) => `  (${q(r.name)}, ${r.lng}, ${r.lat}, ${q(r.venue_type)}, ` +
    `${q(r.access_kind)}, ${q(r.address)}, ${q(r.floor_hint)}, ` +
    `${b(r.wheelchair)}, ${b(r.changing_table)}, ${b(r.gender_neutral)})`)
  .join(',\n')

writeFileSync(join(root, 'supabase/seed.sql'), `-- GENERATED by scripts/seed-to-sql.mjs — edit src/data/seed.json instead.
--
-- ${rows.length} well-known Lower Manhattan locations. NONE verified in person;
-- coordinates are approximate to the building, not the restroom door. No door
-- codes: rows marked code_required simply have no code recorded yet.
-- Amenity flags are null (unknown) rather than guessed.
--
-- Synthetic confirms/troubles from the bundled sample are deliberately NOT
-- carried over — real reports should come from real people.

set search_path = public, extensions;

insert into bathrooms
  (name, geog, venue_type, access_kind, address, floor_hint,
   wheelchair, changing_table, gender_neutral)
select
  v.name,
  st_setsrid(st_makepoint(v.lng, v.lat), 4326)::geography,
  v.venue_type::venue_type,
  v.access_kind::access_kind,
  v.address, v.floor_hint,
  v.wheelchair, v.changing_table, v.gender_neutral
from (values
${values}
) as v(name, lng, lat, venue_type, access_kind, address, floor_hint,
       wheelchair, changing_table, gender_neutral);
`)
console.log(`wrote supabase/seed.sql (${rows.length} rows)`)
